name = "Solstice"
author = "Salem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be0893ec55ae545fcaf856dc103dc7a2c434f1471dc4f4889e925eb618274a08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
