name = "Solstice"
author = "Salem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c60a7e2590af80ec3fb75f3ecbd5e391b58db62f01e069c42fc9fd26b32ba655"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
