name = "Project Solstice"
author = "Salem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "956b00adcb1eeefc6274c8dccb7b48ce7ab7b317b71b6eba7d09ca1b8086b9fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
